package com.example.demo.testMBP;

import org.springframework.boot.test.context.SpringBootTest;

public class BasicInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.id
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.name
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.sex
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.position
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.unit
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.field
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.Effect_research
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String effectResearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.email
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.address
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.postcode
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_information.img
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    private byte[] img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.id
     *
     * @return the value of basic_information.id
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.id
     *
     * @param id the value for basic_information.id
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.name
     *
     * @return the value of basic_information.name
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.name
     *
     * @param name the value for basic_information.name
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.sex
     *
     * @return the value of basic_information.sex
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.sex
     *
     * @param sex the value for basic_information.sex
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.position
     *
     * @return the value of basic_information.position
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.position
     *
     * @param position the value for basic_information.position
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.unit
     *
     * @return the value of basic_information.unit
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.unit
     *
     * @param unit the value for basic_information.unit
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.field
     *
     * @return the value of basic_information.field
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.field
     *
     * @param field the value for basic_information.field
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.Effect_research
     *
     * @return the value of basic_information.Effect_research
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getEffectResearch() {
        return effectResearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.Effect_research
     *
     * @param effectResearch the value for basic_information.Effect_research
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setEffectResearch(String effectResearch) {
        this.effectResearch = effectResearch == null ? null : effectResearch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.email
     *
     * @return the value of basic_information.email
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.email
     *
     * @param email the value for basic_information.email
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.address
     *
     * @return the value of basic_information.address
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.address
     *
     * @param address the value for basic_information.address
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.postcode
     *
     * @return the value of basic_information.postcode
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.postcode
     *
     * @param postcode the value for basic_information.postcode
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_information.img
     *
     * @return the value of basic_information.img
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public byte[] getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_information.img
     *
     * @param img the value for basic_information.img
     *
     * @mbg.generated Thu Nov 19 22:19:02 CST 2020
     */
    public void setImg(byte[] img) {
        this.img = img;
    }
}